### ISSUE TITLE
mLab failed to connect

### ISSUE THREAD

**Issue by amitmad** [meltmedia/dropwizard-mongo#9]
com.mongodb.MongoCommandException: Command failed with error 18: 'auth failed' on server ds00031.mlab.com:00031. The full response is { "ok" : 0.0, "errmsg" : "auth failed", "code" : 18 }

```
mongo:
  seeds:
  - host: ds00031.mlab.com
    port: 00031
  database: dbname
  credentials:
    userName: user
    password: password
```
